apiVersion: apps/v1
kind: Deployment
metadata:
  name: apievent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apievent
  template:
    metadata:
      labels:
        app: apievent
    spec:
      containers:
        - name: apievent
          image: joaogasparini/fiap-event:latest
          ports:
            - containerPort: 81
